- hosts: localhost
  become: no
  vars_files:
    - config/nodes-vmware.yml
  roles:
    - ansible-role-vmware

  post_tasks:
    - debug:
        var: instances.results

    - name: add hosts to webserver group
      add_host:
        name: "{{ item.instance.hw_name | default(item.invocation.module_args.name }}"
        ansible_host: "{{ item.instance.hw_eth0.ipaddresses[0] | default(item.invocation.module_args.netnworks[0].ip }}"
        groups: tag_role_webserver,tag_app_lamp_multi_node
      with_items: "{{ instances.results }}"
      when: ('lamp-web' in item.instance.hw_name | default(item.invocation.module_args.name))
      changed_when: no
      tags:
        - addhost

    - name: add hosts to dbserver group
      add_host:
        name: "{{ item.instance.hw_name | default(item.invocation.module_args.name }}"
        ansible_host: "{{ item.instance.hw_eth0.ipaddresses[0] | default(item.invocation.module_args.netnworks[0].ip }}"
        groups: tag_role_dbserver,tag_app_lamp_multi_node
      with_items: "{{ instances.results }}"
      when: ('lamp-db' in item.instance.hw_name | default(item.invocation.module_args.name))
      changed_when: no
      tags:
        - addhost

    - name: add hosts to lbserver group
      add_host:
        name: "{{ item.instance.hw_name | default(item.invocation.module_args.name }}"
        ansible_host: "{{ item.instance.hw_eth0.ipaddresses[0] | default(item.invocation.module_args.netnworks[0].ip }}"
        groups: tag_role_lbserver,tag_app_lamp_multi_node
      with_items: "{{ instances.results }}"
      when: ('lamp-haproxy' in item.instance.hw_name | default(item.invocation.module_args.name))
      changed_when: no
      tags:
        - addhost