---
- hosts: '*_role_dbserver'
  become: yes
  roles:
  - geerlingguy.mysql

- hosts: '*_role_webserver'
  become: yes
  roles:
  - geerlingguy.nginx

  post_tasks:
  - name: create index.html from template
    template:
      src: index.html.j2
      dest: /usr/share/nginx/html/index.html

- hosts: '*_role_lbserver'
  become: yes
  vars:
    http_port: "{{':'}}80"
    nginx_test_message: Welcome to nginx

  pre_tasks:
  - name: Populate backend servers
    set_fact:
      haproxy_backend_servers: "{{ haproxy_backend_servers|default([]) + [ {'name': hostvars[item].ansible_hostname, 'address': (hostvars[item].ansible_default_ipv4.address | default(hostvars[item].ansible_host)) + http_port } ] }}"
    loop: "{{ groups.tag_role_webserver | default(groups.vmware_tag_role_webserver) | default(groups.label_role_webserver) }}"

  roles:
  - geerlingguy.haproxy

  post_tasks:
  # smoke test that haproxy is serving requests
  - name: proper response from haproxy is received
    uri:
      url: http://{{ ansible_host }}/
      return_content: yes
    register: response
    until: "'This is the sites URL' in response.content"
    retries: 10
    delay: 1
    ignore_errors: yes

  - name: output url
    debug:
      msg: "application is available at http://{{ ansible_host }}/"
    when: response is success
